<?php
return [
    'adminEmail1' => 'admin@example.com1',
    'upload_path' => 'http://59.110.215.21/kx0129',
    'user.passwordResetTokenExpire' => 1000,
    'web1'=>[
        'web_id'=>'1',
        'web_url'=>'index.php?r=site/',
        #产品一级分类
        'product_parent'=>'1',
        #产品首页显示条数
        'index_product_limit'=>'12',
        #产品列表每页显示条数
        'product_limit'=>'12',
        #产品标题
        'product_title'=>'服务项目',
        'product_title_eng'=>'SERVICE PROJECT',
        #新闻分类
        'news_type'=>'1',
        #新闻标题
        'news_title'=>'新闻中心',
        'news_title_eng'=>'NEWS',
        #新闻列表每页显示条数
        'news_limit'=>'10',
        #维修知识
        'news2_type'=>'7',
        'news2_title'=>'维修知识',
        #新闻首页显示条数
        'news_index_limit'=>'7',
        #关于我们
        'article_1'=>'1220',
        'article_title_1'=>'关于我们',
        'article_title_eng_1'=>'ABOUT US',
        #服务中心
        'article_2'=>'1219',
        'article_title_2'=>'服务中心',
        #上门维修
        'article_3'=>'1218',
        'article_title_3'=>'上门维修',
        #联系我们
        'article_4'=>'1217',
        'article_title_4'=>'联系我们',
    ],
    'web2'=>[
        'web_id'=>'2',
        'web_url'=>'index.php?r=site1/',
        #产品一级分类
        'product_parent'=>'9',
        #产品首页显示条数
        'index_product_limit'=>'10',
        #产品列表每页显示条数
        'product_limit'=>'12',
        #维修项目
        'product_title'=>'维修项目',
        'product_title_eng'=>'SERVICE PROJECT',
        #新闻分类
        'news_type'=>'4',
        #新闻标题
        'news_title'=>'新闻中心',
        'news_title_eng'=>'NEWS',
        #新闻列表每页显示条数
        'news_limit'=>'10',
        #维修案例
        'product2_title'=>'维修案例',
        'product2_parent'=>'12',
        #新闻首页显示条数
        'news_index_limit'=>'5',
        #关于我们
        'article_1'=>'1216',
        'article_title_1'=>'关于我们',
        'article_title_eng_1'=>'ABOUT US',
        #售后服务
        'article_2'=>'1215',
        'article_title_2'=>'售后服务',
        #联系方式
        'article_3'=>'1213',
        'article_title_3'=>'联系方式',
        #维修知识
        'news2_type'=>'8',
        'news2_title'=>'维修知识',
    ],
    'web3'=>[
        'web_id'=>'3',
        'web_url'=>'index.php?r=site2/',
        #产品一级分类
        'product_parent'=>'14',
        #产品首页显示条数
        'index_product_limit'=>'8',
        #产品列表每页显示条数
        'product_limit'=>'6',
        #维修项目
        'product_title'=>'维修项目',
        'product_title_eng'=>'PRODUCT',
        #新闻分类
        'news_type'=>'9',
        #新闻标题
        'news_title'=>'新闻动态 ',
        'news_title_eng'=>'NEWS',
        #新闻列表每页显示条数
        'news_limit'=>'10',
        #维修案例
        'product2_title'=>'维修案例',
        'product2_parent'=>'18',
        #新闻首页显示条数
        'news_index_limit'=>'5',
        #关于我们
        'article_1'=>'1221',
        'article_title_1'=>'关于我们',
        'article_title_eng_1'=>'ABOUT US',
        #联系我们
        'article_2'=>'1222',
        'article_title_2'=>'联系我们',
        #售后服务
        'article_3'=>'1223',
        'article_title_3'=>'售后服务',
        #上门维修
        'article_4'=>'1224',
        'article_title_4'=>'上门维修',
        #维修知识
        'news2_type'=>'10',
        'news2_title'=>'维修知识',
    ],
    'web4'=>[
        'web_id'=>'4',
        'web_url'=>'index.php?r=site3/',
        #产品一级分类
        'product_parent'=>'20',
        #产品首页显示条数
        'index_product_limit'=>'10',
        #产品列表每页显示条数
        'product_limit'=>'12',
        #服务项目
        'product_title'=>'服务项目',
        'product_title_eng'=>'PRODUCT',
        #新闻分类
        'news_type'=>'11',
        #新闻标题
        'news_title'=>'新闻中心 ',
        'news_title_eng'=>'NEWS',
        #新闻列表每页显示条数
        'news_limit'=>'10',
        #维修案例
        'product2_title'=>'维修案例',
        'product2_parent'=>'23',
        #新闻首页显示条数
        'news_index_limit'=>'3',
        #关于我们
        'article_1'=>'1225',
        'article_title_1'=>'关于我们',
        'article_title_eng_1'=>'ABOUT US',
        #联系我们
        'article_2'=>'1227',
        'article_title_2'=>'联系我们',
        #售后服务
        'article_3'=>'1226',
        'article_title_3'=>'售后服务',
        #上门维修
        'article_4'=>'1228',
        'article_title_4'=>'上门维修',
        #维修知识
        'news2_type'=>'12',
        'news2_title'=>'维修知识',
    ],
    'web5'=>[
        'web_id'=>'5',
        'web_url'=>'index.php?r=site4/',
        #产品一级分类
        'product_parent'=>'25',
        #产品首页显示条数
        'index_product_limit'=>'10',
        #产品列表每页显示条数
        'product_limit'=>'12',
        #服务项目
        'product_title'=>'我们的服务',
        'product_title_eng'=>'PRODUCT',
        #新闻分类
        'news_type'=>'13',
        #新闻标题
        'news_title'=>'行业新闻 ',
        'news_title_eng'=>'NEWS',
        #新闻列表每页显示条数
        'news_limit'=>'10',
        #维修案例
        'product2_title'=>'精品案例',
        'product2_parent'=>'26',
        #新闻首页显示条数
        'news_index_limit'=>'4',
        #关于我们
        'article_1'=>'1229',
        'article_title_1'=>'关于我们',
        'article_title_eng_1'=>'ABOUT US',
        #联系我们
        'article_2'=>'1231',
        'article_title_2'=>'联系我们',
        #售后服务
        'article_3'=>'1230',
        'article_title_3'=>'行业解决方案',
        #上门维修
        'article_4'=>'1228',
        'article_title_4'=>'上门维修',
        #维修知识
        'news2_type'=>'14',
        'news2_title'=>'行业门户',
    ],
    'web6'=>[
        'web_id'=>'6',
        'web_url'=>'index.php?r=site5/',
        #产品一级分类
        'product_parent'=>'30',
        #产品首页显示条数
        'index_product_limit'=>'10',
        #产品列表每页显示条数
        'product_limit'=>'12',
        #服务项目
        'product_title'=>'服务项目',
        'product_title_eng'=>'PRODUCT',
        #新闻分类
        'news_type'=>'15',
        #新闻标题
        'news_title'=>'新闻中心 ',
        'news_title_eng'=>'NEWS',
        #新闻列表每页显示条数
        'news_limit'=>'10',
        #维修案例
        'product2_title'=>'维修案例',
        'product2_parent'=>'31',
        #新闻首页显示条数
        'news_index_limit'=>'10',
        #关于我们
        'article_1'=>'1232',
        'article_title_1'=>'关于我们',
        'article_title_eng_1'=>'ABOUT US',
        #联系我们
        'article_2'=>'1233',
        'article_title_2'=>'联系我们',
        #售后服务
        'article_3'=>'1234',
        'article_title_3'=>'售后服务',
        #上门维修
        'article_4'=>'1228',
        'article_title_4'=>'上门维修',
        #维修知识
        'news2_type'=>'16',
        'news2_title'=>'维修知识',
    ],
    'web7'=>[
        'web_id'=>'7',
        'web_url'=>'index.php?r=site5/',
        #产品一级分类
        'product_parent'=>'35',
        #产品首页显示条数
        'index_product_limit'=>'10',
        #产品列表每页显示条数
        'product_limit'=>'12',
        #服务项目
        'product_title'=>'服务项目',
        'product_title_eng'=>'PRODUCT',
        #新闻分类
        'news_type'=>'17',
        #新闻标题
        'news_title'=>'新闻中心 ',
        'news_title_eng'=>'NEWS',
        #新闻列表每页显示条数
        'news_limit'=>'10',
        #维修案例
        'product2_title'=>'维修案例',
        'product2_parent'=>'36',
        #新闻首页显示条数
        'news_index_limit'=>'10',
        #关于我们
        'article_1'=>'1235',
        'article_title_1'=>'关于我们',
        'article_title_eng_1'=>'ABOUT US',
        #联系我们
        'article_2'=>'1237',
        'article_title_2'=>'联系我们',
        #售后服务
        'article_3'=>'1236',
        'article_title_3'=>'售后服务',
        #上门维修
        'article_4'=>'1228',
        'article_title_4'=>'上门维修',
        #维修知识
        'news2_type'=>'18',
        'news2_title'=>'维修知识',
    ],
    'web8'=>[
        'web_id'=>'8',
        'web_url'=>'index.php?r=site5/',
        #产品一级分类
        'product_parent'=>'35',
        #产品首页显示条数
        'index_product_limit'=>'10',
        #产品列表每页显示条数
        'product_limit'=>'12',
        #服务项目
        'product_title'=>'服务项目',
        'product_title_eng'=>'PRODUCT',
        #新闻分类
        'news_type'=>'17',
        #新闻标题
        'news_title'=>'新闻中心 ',
        'news_title_eng'=>'NEWS',
        #新闻列表每页显示条数
        'news_limit'=>'10',
        #维修案例
        'product2_title'=>'维修案例',
        'product2_parent'=>'36',
        #新闻首页显示条数
        'news_index_limit'=>'10',
        #关于我们
        'article_1'=>'1235',
        'article_title_1'=>'关于我们',
        'article_title_eng_1'=>'ABOUT US',
        #联系我们
        'article_2'=>'1237',
        'article_title_2'=>'联系我们',
        #售后服务
        'article_3'=>'1236',
        'article_title_3'=>'售后服务',
        #上门维修
        'article_4'=>'1228',
        'article_title_4'=>'上门维修',
        #维修知识
        'news2_type'=>'18',
        'news2_title'=>'维修知识',
    ],
    'web9'=>[
        'web_id'=>'9',
        'web_url'=>'index.php?r=site/',
        #产品一级分类
        'product_parent'=>'90',
        #产品首页显示条数
        'index_product_limit'=>'10',
        #产品列表每页显示条数
        'product_limit'=>'12',
        #服务项目
        'product_title'=>'服务项目',
        'product_title_eng'=>'PRODUCT',
        #新闻分类
            'news_type'=>'19',
        #新闻标题
        'news_title'=>'新闻中心 ',
        'news_title_eng'=>'NEWS',
        #新闻列表每页显示条数
        'news_limit'=>'10',
        #维修案例
        'product2_title'=>'维修案例',
        'product2_parent'=>'92',
        #新闻首页显示条数
        'news_index_limit'=>'10',
        #关于我们
        'article_1'=>'1242',
        'article_title_1'=>'关于我们',
        'article_title_eng_1'=>'ABOUT US',
        #联系我们
        'article_2'=>'1243',
        'article_title_2'=>'联系我们',
        #售后服务
        'article_3'=>'1244',
        'article_title_3'=>'售后服务',
        #上门维修
        'article_4'=>'1245',
        'article_title_4'=>'上门维修',
        #维修知识
        'news2_type'=>'20',
        'news2_title'=>'维修知识',
    ],
    'web10'=>[
        'web_id'=>'10',
        'web_url'=>'index.php?r=site/',
        #产品一级分类
        'product_parent'=>'94',
        #产品首页显示条数
        'index_product_limit'=>'10',
        #产品列表每页显示条数
        'product_limit'=>'12',
        #服务项目
        'product_title'=>'服务项目',
        'product_title_eng'=>'PRODUCT',
        #新闻分类
        'news_type'=>'21',
        #新闻标题
        'news_title'=>'新闻中心1',
        'news_title_eng'=>'NEWS',
        #新闻列表每页显示条数
        'news_limit'=>'10',
        #维修案例
        'product2_title'=>'维修案例',
        'product2_parent'=>'95',
        #新闻首页显示条数
        'news_index_limit'=>'4',
        #关于我们
        'article_1'=>'1246',
        'article_title_1'=>'关于我们',
        'article_title_eng_1'=>'ABOUT US',
        #联系我们
        'article_2'=>'1247',
        'article_title_2'=>'联系我们',
        #售后服务
        'article_3'=>'1248',
        'article_title_3'=>'售后服务',
        #上门维修
        'article_4'=>'1249',
        'article_title_4'=>'上门维修',
        #维修知识
        'news2_type'=>'22',
        'news2_title'=>'新闻中心2',
        #分类1
        'classs1'=>'113',
        #分类2
        'classs2'=>'115',
        #分类3
        'classs3'=>'116',
        #分类4
        'classs4'=>'113',
    ],
    'web11'=>[
        'web_id'=>'11',
        'web_url'=>'index.php?r=site3/',
        #产品首页显示条数
        'index_product_limit'=>'10',
        #产品列表每页显示条数
        'product_limit'=>'12',
        #服务项目
        'product_title'=>'服务项目',
        'product_title_eng'=>'PRODUCT',
        #产品一级分类
        'product_parent'=>'96',
        #维修案例
        'product2_parent'=>'97',
        'product2_title'=>'维修案例',
        #新闻标题
        'news_title'=>'新闻中心 ',
        'news_title_eng'=>'NEWS',
        #新闻分类
        'news_type'=>'23',
        #维修知识
        'news2_type'=>'24',
        'news2_title'=>'维修知识',
        #新闻列表每页显示条数
        'news_limit'=>'10',
        #新闻首页显示条数
        'news_index_limit'=>'10',
        #关于我们
        'article_1'=>'1250',
        'article_title_1'=>'关于我们',
        'article_title_eng_1'=>'ABOUT US',
        #联系我们
        'article_2'=>'1251',
        'article_title_2'=>'联系我们',
        #售后服务
        'article_3'=>'1252',
        'article_title_3'=>'售后服务',
        #上门维修
        'article_4'=>'1253',
        'article_title_4'=>'上门维修',
    ],
    'web12'=>[
        'web_id'=>'12',
        'web_url'=>'index.php?r=site3/',
        #产品首页显示条数
        'index_product_limit'=>'10',
        #产品列表每页显示条数
        'product_limit'=>'12',
        #服务项目
        'product_title'=>'服务项目',
        'product_title_eng'=>'PRODUCT',
        #产品一级分类
        'product_parent'=>'102',
        #维修案例
        'product2_parent'=>'104',
        'product2_title'=>'维修案例',
        #新闻标题
        'news_title'=>'新闻中心 ',
        'news_title_eng'=>'NEWS',
        #新闻分类
        'news_type'=>'25',
        #维修知识
        'news2_type'=>'26',
        'news2_title'=>'维修知识',
        #新闻列表每页显示条数
        'news_limit'=>'10',
        #新闻首页显示条数
        'news_index_limit'=>'10',
        #文章1
        'article_1'=>'1254',
        'article_title_1'=>'关于我们',
        'article_title_eng_1'=>'ABOUT US',
        #文章2
        'article_2'=>'1255',
        'article_title_2'=>'联系我们',
        #文章3
        'article_3'=>'1256',
        'article_title_3'=>'售后服务',
        #文章4
        'article_4'=>'1257',
        'article_title_4'=>'上门维修',
    ],
];
